## @file
# Azure Pipeline build file for building platforms with VS.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: main

variables:
- group: tool-chain-windows-visual-studio-latest

jobs:
- template: Platform-Build-Job.yml
  parameters:
    extra_install_step:
    - powershell: choco install qemu --version=2022.8.31; Write-Host "##vso[task.prependpath]c:\Program Files\qemu"
      displayName: Install QEMU and Set QEMU on path # friendly name displayed in the UI
      condition: and(gt(variables.pkg_count, 0), succeeded())
    tool_chain_tag: 'VS2022'
    vm_image: $(vm_image)
