## @file
# Azure Pipeline build file for building platforms with GCC.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: main
  containers:
    - container: linux-gcc
      image: ghcr.io/microsoft/mu_devops/ubuntu-24-test:latest
      options: --name mu_devops_build_container

variables:
- group: tool-chain-ubuntu-gcc

jobs:
- template: Platform-Build-Job.yml
  parameters:
    tool_chain_tag: 'GCC5'
    vm_image: $(vm_image)
    os_type: Linux
    container_image: linux-gcc
    build_matrix:
      QemuQ35_IA32X64_DEBUG:
        BuildPackage: QemuQ35Pkg
        BuildFile: "Platforms/QemuQ35Pkg/PlatformBuild.py"
        BuildFlags: "-a IA32,X64"
        BuildTarget: "DEBUG"
        BuildExtraTag: "IA32X64"
        BuildExtraStep:
          - script: echo No extra steps provided
        Run: false
        RunFlags: "SHUTDOWN_AFTER_RUN=TRUE QEMU_HEADLESS=TRUE EMPTY_DRIVE=TRUE BLD_*_QEMU_CORE_NUM=2 TEST_REGEX=*TestApp*.efi RUN_TESTS=TRUE"
        BuildArtifactsBinary: |
          **/QEMUQ35_*.fd
        BuildArtifactsOther: "**/unit_test_results/*"
