## @file
# Azure Pipeline build file for building platforms with VS.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: main

variables:
- group: tool-chain-windows-visual-studio-latest

jobs:
- template: Platform-Build-Job.yml
  parameters:
    extra_install_step:
    - powershell: choco install qemu --version=2022.8.31; Write-Host "##vso[task.prependpath]c:\Program Files\qemu"
      displayName: Install QEMU and Set QEMU on path # friendly name displayed in the UI
      condition: and(gt(variables.pkg_count, 0), succeeded())
    tool_chain_tag: 'VS2022'
    vm_image: $(vm_image)
    os_type: Windows_NT
    build_matrix:
      QemuQ35_DEBUG:
        BuildPackage: QemuQ35Pkg
        BuildFile: "Platforms/QemuQ35Pkg/PlatformBuild.py"
        BuildArch: IA32,X64
        BuildFlags: ""
        BuildTarget: "DEBUG"
        BuildExtraTag: ""
        BuildExtraStep:
          - script: echo No extra steps provided
        Run: true
        RunFlags: "SHUTDOWN_AFTER_RUN=TRUE QEMU_HEADLESS=TRUE EMPTY_DRIVE=TRUE BLD_*_QEMU_CORE_NUM=2 TEST_REGEX=*TestApp*.efi RUN_TESTS=TRUE"
        BuildArtifactsBinary: |
          **/QEMUQ35_*.fd
        BuildArtifactsOther: "**/unit_test_results/*"

      QemuQ35_RELEASE:
        BuildPackage: QemuQ35Pkg
        BuildFile: "Platforms/QemuQ35Pkg/PlatformBuild.py"
        BuildArch: IA32,X64
        BuildFlags: ""
        BuildTarget: "RELEASE"
        BuildExtraTag: ""
        BuildExtraStep:
          - script: echo No extra steps provided
        Run: true
        RunFlags: "SHUTDOWN_AFTER_RUN=TRUE QEMU_HEADLESS=TRUE EMPTY_DRIVE=TRUE BLD_*_QEMU_CORE_NUM=2 TEST_REGEX=*TestApp*.efi RUN_TESTS=TRUE"
        BuildArtifactsBinary: |
          **/QEMUQ35_*.fd
        BuildArtifactsOther: "**/unit_test_results/*"

      QemuQ35_DEBUG_ARM:
        BuildPackage: QemuQ35Pkg
        BuildFile: "Platforms/QemuQ35Pkg/PlatformBuild.py"
        BuildArch: IA32,X64
        BuildFlags: ""
        BuildTarget: "DEBUG"
        BuildExtraTag: "ON_ARM"
        BuildExtraStep:
          - script: echo No extra steps provided
        Run: false
        RunFlags: "SHUTDOWN_AFTER_RUN=TRUE QEMU_HEADLESS=TRUE EMPTY_DRIVE=TRUE BLD_*_QEMU_CORE_NUM=2 TEST_REGEX=*TestApp*.efi RUN_TESTS=TRUE"
        SelfHostAgent: true
        BuildArtifactsBinary: |
          **/QEMUQ35_*.fd
          **/*/*TestApp.efi
        BuildArtifactsOther: "**/unit_test_results/*"

      QemuQ35_RELEASE_ARM:
        BuildPackage: QemuQ35Pkg
        BuildFile: "Platforms/QemuQ35Pkg/PlatformBuild.py"
        BuildArch: IA32,X64
        BuildFlags: ""
        BuildTarget: "RELEASE"
        BuildExtraTag: "ON_ARM"
        BuildExtraStep:
          - script: echo No extra steps provided
        Run: false
        RunFlags: "SHUTDOWN_AFTER_RUN=TRUE QEMU_HEADLESS=TRUE EMPTY_DRIVE=TRUE BLD_*_QEMU_CORE_NUM=2 TEST_REGEX=*TestApp*.efi RUN_TESTS=TRUE"
        SelfHostAgent: true
        BuildArtifactsBinary: |
          **/QEMUQ35_*.fd
          **/*/*TestApp.efi
        BuildArtifactsOther: "**/unit_test_results/*"

      QemuQ35_NO_SMM_RELEASE:
        BuildPackage: QemuQ35Pkg
        BuildFile: "Platforms/QemuQ35Pkg/PlatformBuild.py"
        BuildArch: IA32,X64
        BuildFlags: "BLD_*_SMM_ENABLED=FALSE"
        BuildTarget: "RELEASE"
        BuildExtraTag: "NO_SMM"
        BuildExtraStep:
          - script: echo No extra steps provided
        Run: true
        RunFlags: "SHUTDOWN_AFTER_RUN=TRUE QEMU_HEADLESS=TRUE BLD_*_QEMU_CORE_NUM=2 BLD_*_SMM_ENABLED=FALSE"
        BuildArtifactsBinary: |
          **/QEMUQ35_*.fd
        BuildArtifactsOther: ""
