# @file publish-mdbook.yml
#
# A GitHub workflow that compiles the mdbook located at docs/* and publishes it
# to the repository's GitHub Pages site.
#
##
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

name: Publish Documentation

on:
  # Trigger this workflow manually if necessary
  workflow_dispatch:

  # Triggers this workflow if a commit is pushed to main in which a file in
  # docs/** has been updated
  push:
    branches:
      - main
    paths:
      - docs/**
      - .github/workflows/publish-mdbook.yml

jobs:
  build:
    name: Build Documentation

    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout Repository ✅
        uses: actions/checkout@v4

      - name: 🛠️ Install mdbook Toolchain 🛠️
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook,mdbook-admonish,mdbook-mermaid,mdbook-linkcheck

      - name: 📄 Build Documentation 📄
        run: mdbook build docs

      - name: Upload GitHub Pages Site Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: docs/book/html

  publish:
    if: github.repository_owner == 'microsoft'
    name: Publish Documentation

    needs: [build]

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      id-token: write
      contents: read
      pages: write

    steps:
      - name: 🚀 Deploy GitHub Pages Site 🚀
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ github.token }}
          artifact_name: github-pages
